### ISSUE TITLE
failed to parse C_USE_SERVANT_FEED_ITEM<1>

### ISSUE THREAD

**Issue by BamV** [RobinNorling/pet-repop#1]
im getting this error

[17:45:16.064] [dispatch] handle: failed to parse C_USE_SERVANT_FEED_ITEM<1>
hook: (anonymous) in pet-repop
data: 14006f9489a2050000000000e124030000000000
error: definition.reader is not a function
    at TeraProtocol.parse (C:\Users\Pichau\AppData\Local\Programs\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:467:27)
[17:45:19.963] [dispatch] handle: failed to parse C_USE_SERVANT_FEED_ITEM<1>
hook: (anonymous) in pet-repop
data: 14006f9489a2050000000000e124030000000000
error: definition.reader is not a function
    at TeraProtocol.parse (C:\Users\Pichau\AppData\Local\Programs\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:467:27)
[17:45:23.983] [dispatch] handle: failed to parse C_USE_SERVANT_FEED_ITEM<1>
hook: (anonymous) in pet-repop
data: 14006f9489a2050000000000e124030000000000
error: definition.reader is not a function
    at TeraProtocol.parse (C:\Users\Pichau\AppData\Local\Programs\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:467:27)
[17:45:48.927] [dispatch] handle: failed to parse C_START_SERVANT_ACTIVE_SKILL<1>
hook: (anonymous) in pet-repop
data: 100079748465030000800e004d040000
error: definition.reader is not a function
    at TeraProtocol.parse (C:\Users\Pichau\AppData\Local\Programs\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:467:27)

**Comment by RobinNorling** [comment]
yeah, Caali remade some shit, it's fixed now 👍

**Comment by BamV** [comment]
thx
